name: ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      
    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: |
        CGO_ENABLED=0 go test ./...
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/foo-api
        tags: ${{ github.sha }}, latest

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: maxkrivich/do-argocd-apps
        event-type: argocd-image-update
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "image_name": "${{ secrets.DOCKER_USERNAME }}/foo-api:${{ github.sha }}", "kustomize_image": "foo-api", "app_name": "foo"}'
